//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTSharp.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_pt_br() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTSharp.Domain.Resources.Messages_pt-br", typeof(Messages_pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a e-mail.
        /// </summary>
        internal static string L_Email {
            get {
                return ResourceManager.GetString("L_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a senha.
        /// </summary>
        internal static string L_Password {
            get {
                return ResourceManager.GetString("L_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} e {1} são iguais.
        /// </summary>
        internal static string V_AreEquals {
            get {
                return ResourceManager.GetString("V_AreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} e {1} não são iguais.
        /// </summary>
        internal static string V_AreNotEqual {
            get {
                return ResourceManager.GetString("V_AreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} contem {1}.
        /// </summary>
        internal static string V_Contains {
            get {
                return ResourceManager.GetString("V_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} tem o mesmo tamanho {1} de caractere(s).
        /// </summary>
        internal static string V_HasExactLengthIfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_HasExactLengthIfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} tem tamanho {1}.
        /// </summary>
        internal static string V_HasLen {
            get {
                return ResourceManager.GetString("V_HasLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} tem tamanho maior que {1} caractere(s).
        /// </summary>
        internal static string V_HasMaxLen {
            get {
                return ResourceManager.GetString("V_HasMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} tem tamanho maior que {1} caractere(s).
        /// </summary>
        internal static string V_HasMaxLengthIfNotNullOrEmptHasMaxLengthIfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_HasMaxLengthIfNotNullOrEmptHasMaxLengthIfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} tem tamanho menor que {1} caractere(s).
        /// </summary>
        internal static string V_HasMinLen {
            get {
                return ResourceManager.GetString("V_HasMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} tem tamanho menor que {1} caractere(s).
        /// </summary>
        internal static string V_HasMinLengthIfNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_HasMinLengthIfNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} está entre {1} e {2}.
        /// </summary>
        internal static string V_IsBetween {
            get {
                return ResourceManager.GetString("V_IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é numérico.
        /// </summary>
        internal static string V_IsDigit {
            get {
                return ResourceManager.GetString("V_IsDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} e-mail válido.
        /// </summary>
        internal static string V_IsEmail {
            get {
                return ResourceManager.GetString("V_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} e-mail válido ou vazio.
        /// </summary>
        internal static string V_IsEmailOrEmpty {
            get {
                return ResourceManager.GetString("V_IsEmailOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é vazio.
        /// </summary>
        internal static string V_IsEmpty {
            get {
                return ResourceManager.GetString("V_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é falso.
        /// </summary>
        internal static string V_IsFalse {
            get {
                return ResourceManager.GetString("V_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é maior ou igual a {1}.
        /// </summary>
        internal static string V_IsGreaterOrEqualsThan {
            get {
                return ResourceManager.GetString("V_IsGreaterOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é maior que {1}.
        /// </summary>
        internal static string V_IsGreaterThan {
            get {
                return ResourceManager.GetString("V_IsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é menor ou igual a {1}.
        /// </summary>
        internal static string V_IsLowerOrEqualsThan {
            get {
                return ResourceManager.GetString("V_IsLowerOrEqualsThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é menor que {1}.
        /// </summary>
        internal static string V_IsLowerThan {
            get {
                return ResourceManager.GetString("V_IsLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não é e-mail válido.
        /// </summary>
        internal static string V_IsNotEmail {
            get {
                return ResourceManager.GetString("V_IsNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não está vazio.
        /// </summary>
        internal static string V_IsNotEmpty {
            get {
                return ResourceManager.GetString("V_IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não é maior que {1}.
        /// </summary>
        internal static string V_IsNotGreaterThan {
            get {
                return ResourceManager.GetString("V_IsNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não é null.
        /// </summary>
        internal static string V_IsNotNull {
            get {
                return ResourceManager.GetString("V_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não é null ou empty.
        /// </summary>
        internal static string V_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("V_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não é null ou espaço em branco.
        /// </summary>
        internal static string V_IsNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("V_IsNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é null.
        /// </summary>
        internal static string V_IsNull {
            get {
                return ResourceManager.GetString("V_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é null ou vazio.
        /// </summary>
        internal static string V_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("V_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é null ou nullable.
        /// </summary>
        internal static string V_IsNullOrNullable {
            get {
                return ResourceManager.GetString("V_IsNullOrNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é verdadeiro.
        /// </summary>
        internal static string V_IsTrue {
            get {
                return ResourceManager.GetString("V_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é url.
        /// </summary>
        internal static string V_IsUrl {
            get {
                return ResourceManager.GetString("V_IsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é url ou vazio.
        /// </summary>
        internal static string V_IsUrlOrEmpty {
            get {
                return ResourceManager.GetString("V_IsUrlOrEmpty", resourceCulture);
            }
        }
    }
}
